name: smart_kharcha
description: A simple expense tracking app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  introduction_screen: ^4.0.0
  provider: ^6.1.2
  url_launcher: ^6.2.0
  intl: ^0.19.0
  path_provider: ^2.1.2
  pdf: ^3.10.7
  excel: ^4.0.0
  csv: ^6.0.0
  share_plus: ^10.1.0
  fl_chart: ^0.66.0
  shimmer: ^3.0.0
  permission_handler: ^12.0.1
  printing: ^5.11.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#2563EB"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  remove_alpha_ios: true
 



flutter:
  uses-material-design: true

  assets:
    - assets/icons/app_icon.png
  
    




